### ISSUE TITLE
Are we allow to add dead HDL made by famous computer scientist?

### ISSUE THREAD

**Issue by hungrymonkey** [drom/awesome-hdl#14]
https://inf.ethz.ch/personal/wirth/Lola/

LOLA, made by Niklaus Wirth

https://en.wikipedia.org/wiki/Niklaus_Wirth
https://inf.ethz.ch/personal/wirth/Lola/LolaCompiler.pdf

**Comment by combinatorylogic** [comment]
It's not quite dead yet - it's used as a part of Project Oberon.

**Comment by drom** [comment]
I have great respect for everything done by Niklaus!
Can you PR LOLA?

**Comment by hungrymonkey** [comment]
sure

**Comment by hungrymonkey** [comment]
@combinatorylogic The lola compiler is written in .Mod.txt. I am not sure of any language that can compile such a format

**Comment by hungrymonkey** [comment]
I believe the Lola compiler is written in Oberon-07 since the code uses `INTEGER` instead of LONGINT or SHORTINT

https://inf.ethz.ch/personal/wirth/Oberon/PortingOberon.pdf

**Comment by hungrymonkey** [comment]
`(NW 8.1.95 / 11.4.2019)`

This version scheme is pretty unhelpful with providing information on the Oberon compiler dialect.

`(Niklaus Wirth.   Creation Date/Revision Data)`

**Comment by hungrymonkey** [comment]
Opps, I am sorry if I accidentally ping you too often.
