### ISSUE TITLE
Could you please add my tool in your list?

### ISSUE THREAD

**Issue by WilsonChen003** [drom/awesome-hdl#57]
Hi, Drom
  Nice to meet you, you tools list is really interesting!
 While I recently developed a tool which natively compatibale with exsting HDL and has a few features to improve efficiency, named HDLGen, the git link is:
  https://github.com/WilsonChen003/HDLGen
 Could you please help?

Best Regards,
Wilson

**Comment by drom** [comment]
Thank you for very interesting tool.
Added the link and short description.
